name: Flatpak
on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: resticat.flatpak
        manifest-path: com.quexten.Resticat.yml
        cache-key: flatpak-builder- github.sha 
    - uses: JasonEtco/upload-to-release@master
      with:
        args: resticat.flatpak
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}